plugins:
  zoco:
    class: KarambolZocoPlugin\ZocoPlugin
    options:
      boamp:
        # Répertoire de base où stocker les archives/XML du BOAMP, relatif au répertoire de l'application Karambol
        data_dir: data/zoco
        # Définition du serveur FTP sur lequel télécharger les fichiers du BOAMP
        ftp:
          host: echanges.dila.gouv.fr
          user: anonymous
          password: anonymous
          base_remote_dir: BOAMP
      elasticsearch:
        hosts: ['http://127.0.0.1:9200/']
        index:
          name: zoco
          settings:
            analysis:
              analyzer:
                default:
                  type: french
            index:
              mapping:
                ignore_malformed: true
          mappings:
            boamp:
              dynamic_templates:
                - DONNEES.RECTIF.MODIFICATION.LIRE:
                    path_match: "*.DONNEES.RECTIF.MODIFICATION.LIRE"
                    mapping:
                      type: string
                - DONNEES.RECTIF.MODIFICATION.TXT_INIT:
                    path_match: "*.DONNEES.RECTIF.MODIFICATION.TXT_INIT"
                    mapping:
                      type: string
assets:
  zoco-plugin:
    - { src: vendor/bornholm/karambol-plugin-zoco/public/css, dest: public/plugins/zoco/css }
    - { src: vendor/bornholm/karambol-plugin-zoco/public/js, dest: public/plugins/zoco/js }
