plugins:
  zoco:
    class: KarambolZocoPlugin\ZocoPlugin
    options:
      boamp:
        # Répertoire de base où stocker les archives/XML du BOAMP, relatif au répertoire de l'application Karambol
        data_dir: data/zoco
        # Définition du serveur FTP sur lequel télécharger les fichiers du BOAMP
        ftp:
          host: echanges.dila.gouv.fr
          user: anonymous
          password: anonymous
          base_remote_dir: BOAMP
      elasticsearch:
        hosts: ['http://127.0.0.1:9200/']
        index:
          name: zoco
          settings:
            analysis:
              analyzer:
                default:
                  type: french
          mappings:
            boamp:
              dynamic_templates:
                - modifications:
                    path_match: "modifications.*-*"
                    mapping:
                      type: nested
                      stored: true
                - modification_txt_init:
                    path_match: "*.DONNEES.RECTIF.MODIFICATION.TXT_INIT"
                    mapping:
                      type: string
                - modification_lire:
                    path_match: "*.DONNEES.RECTIF.MODIFICATION.LIRE"
                    mapping:
                      type: string
